### PR TITLE
feat: disable mkcert default install

### PR DESCRIPTION
**Pull request by 6za**
Depends on update on template: 
- https://github.com/kubefirst/gitops-template/pull/244

Solves: 
- #920 
- #912

Other changes:
- Make `mkcert -install` an user action, to prevent need of sudo access to installer 
- guides user on how to install cert
- update some var names to follow golang conventions 

Signed-off-by: 6za <53096417+6za@users.noreply.github.com>

### CODE REVIEW

**Comment by 6za** [comment]
If you want to explore more mkcert possibilities, this dockerfile can help:
```Dockerfile
FROM --platform=linux/amd64 buildpack-deps:bullseye-scm
RUN apt-get update && \
    apt-get install -y unzip curl jq vim unzip less wget libnss3-tools sudo \
     && rm -rf /var/lib/apt/lists/* 
RUN useradd -ms /bin/bash developer
#USER developer
WORKDIR /home/developer
RUN  wget https://github.com/FiloSottile/mkcert/releases/download/v1.4.4/mkcert-v1.4.4-linux-amd64
RUN chmod +x mkcert-v1.4.4-linux-amd64 && mv mkcert-v1.4.4-linux-amd64 mkcert
```

**Comment by 6za** [comment]
Based on tests: 
- `mkcert -install` can be executed before or after certs are generated 
- `mkcert -CAROOT` shows where the root cert is stored, files added to the trust chain of users OS.
- `mkcert -key-file key.pem -cert-file cert.pem example.com *.example.com` will generate certificates and return `exit 0` even if the keystore is not trusted. 
- Generate and Trust are 2 different actions

**Comment by 6za** [comment]
New user warning: 
```
Notes:
  Kubefirst generated certificates using 'mkcert' for your convenience
   If you have root access you could run:
  .../_tmp_k3d_user/.k1/tools/mkcert -install
  This will update yours OS truststore allowing our certs to be trusted
  by your browser and more smooth expirience
  Learn more at: https://github.com/FiloSottile/mkcert#changing-the-
  location-of-the-ca-files
```

**Comment by 6za** [comment]
Sample of certificate generated: 
image

**Comment by 6za** [comment]
```bash
  ----------------------------------------------------------------------
  Cluster "kubefirst" is up and running!:
  This information is available at $HOME/.kubefirst

  Access the kubefirst-console from your browser at:
  https://kubefirst.localdev.me

  Press ESC to leave this screen and return to your shell.

  Notes:
    Kubefirst generated certificates to ensure secure connections to
    your local deployment. Even if your browser warn you about the
    origin, you can use Kubefirst without any issue.
    If you want, you can update your OS trust store by running
    this command and pass your root password:
      /Users/user/.k1/tools/mkcert -install
    Details:
    https://github.com/FiloSottile/mkcert#changing-the-location-of-the-ca
  -files
  --- Github -----------------------------------------------------------
```

**Review by pagottoo — APPROVED** [review]

**Pull request merged**
