### PR TITLE
docs: update local go run for devs

### PR DESCRIPTION
**Pull request by converge**
Signed-off-by: João Vanzuita <joao@kubeshop.io>

### CODE REVIEW

**Comment by fharper** [comment]
Why do we need this flag? I can run kubefirst local from the latest code in `main` using `go run . local`.

**Comment by converge** [comment]
> Why do we need this flag? I can run kubefirst local from the latest code in `main` using `go run . local`.

I just tried it yesterday, it failed to download the metaphor-frontend template. I'll try it again today

**Comment by fharper** [comment]
Oh no, my bad, I tried last week, and it was working, but something changed, and I got the "panic: Error cloning repo with fallback: error cloning template, No templates found on branch or tag" error.

**Comment by converge** [comment]
> Oh no, my bad, I tried last week, and it was working, but something changed, and I got the "panic: Error cloning repo with fallback: error cloning template, No templates found on branch or tag" error.

awesome! I'll wait the outcome of the ldflag discussion -> update the code -> test to make sure it's working without flags -> update the docs again.

**Review by fharper — APPROVED** [review]
LGTM, as you wrote, we can update now, and update again if that changes with the latest discussion on the flags.

**Pull request merged**
