### PR TITLE
fix: stty

### PR DESCRIPTION
**Pull request by CristhianF7**

### CODE REVIEW

**Comment by fharper** [comment]
When squashing, add (fix #2176) to the commit title please :)

**Comment by CristhianF7** [comment]
Hey @fharper, this is still a draft until we confirm that this fix solves the issue

**Comment by fharper** [comment]
For anyone else, the discussion about this PR are happening at https://github.com/kubefirst/kubefirst/issues/2176

**Comment by CristhianF7** [comment]
Closing in favor of https://github.com/kubefirst/kubefirst/pull/2220

**Pull request closed without merging**
