### PR TITLE
feat: add segment.io as telemetry service

### LINKED ISSUE #491: cmd version has no version
observed behavior:

cmd version command is showing empty version when git clone repo.

expected behavior:

cmd version shows version information when git clone.

AC1: it does shows version when cmd version is called
AC2: ldflags still works when new release

### LINKED ISSUE #499: segment.io integration
As a Kubefirst user I want to collect metrics during the installation process so that I know better how Im experiencing the installation on a user stand point from start to finish.

**Acceptance criteria:**
AC1: it uses official Segment.io Golang library[1]
AC2: the implementation is feature parity[2] with Datadog
AC3: previous telemetry implementation still works for user running previous Kubefirst installer
AC4: the implementation is loosely coupled to allow unit tests
AC5: there are unit tests (at least some)
AC6: there are Segment.io documentation at docs.kubefirst.com describing how we use Segment.io
AC7: segment.io is default, and doesn't require a new flag
AC8: metrics are associated with user domain, and Kubefirst cli version
AC9: We need to be able to privately dashboard this information with varying time granularity (last hour, last 2 months, etc)

[1] https://github.com/segmentio/analytics-go
[2] events captured: init started, init completed, cluster create started, cluster create completed

### Details

Today (as of 1.9), we implement our telemetry MVP leveraging a custom metric microservice named telemetry that runs in our mgmt account so we can measure the frequency and success rate of init and create commands. This is implemented with 4 calls in kubefirst/kubefirst that look approximately like this:

https://github.com/kubefirst/kubefirst/blob/70f3d268040ac8af921b5416d53113f8138e9b06/cmd/createUtils.go#L51

*Note: We must KEEP the telemetry microservice operational until we're convinced nobody is using the older cli versions that leveraged this microservice. (probably a few months out)*

### PR DESCRIPTION
**Pull request by converge**
this PR:

- remove previous telemetry implementation
- add SegmentIO to handle telemetry
- SegmentIO has a JavaScript function(destination) to forward telemetry data to DataDog
- fix cmd version command (required for telemetry data) #491 

closes #499 closes #491 

Signed-off-by: João Vanzuita <joao@kubeshop.io>

### CODE REVIEW

**Comment by 6za** [comment]
Is this PR ready for review? Are we removing the old telemetry? 

As I understood, we would continue to feed metric to the old place until we feel ready to replace. 
https://github.com/kubefirst/kubefirst/issues/499#issuecomment-1268546969

**Comment by converge** [comment]
> Is this PR ready for review? Are we removing the old telemetry?

that's right, I was waiting the today's release first to ask for review.

> 
> As I understood, we would continue to feed metric to the old place until we feel ready to replace. [#499 (comment)](https://github.com/kubefirst/kubefirst/issues/499#issuecomment-1268546969)

that's also correct, we're actually doing that following this approach: starting from this PR and upcoming releases, the installer uses SegmentIO, for previous kubefirst versions App Runner is still in place to handle telemetry.

**Comment by 6za** [comment]
So, to calculate new install we would have to add the 2 dashboards?

**Comment by converge** [comment]
> So, to calculate new install we would have to add the 2 dashboards?

previous and this PR uses the same metric names[1], there were no required changes in the dashboard 

https://github.com/kubefirst/kubefirst/pull/508/files#diff-63e3490c1939ebc33c6a79bf6843562e7d8e2104842fbed9b44b520413ca47edR14

**Review by johndietz — APPROVED** [review]

**Pull request merged**
