### PR TITLE
feat: add GitHub ED25519 ssh keys for github

### PR DESCRIPTION
**Pull request by converge**
Q: why not use `golang.org/x/crypto/ed25519` only and avoid adding a new library to the app?

A: marshalling ED25519 using openssh format is a pending PR at Go development for the past years, and it wasn't merged it. Adding a third party library was necessary to parse the key into the right openssh format.

ticket reference: #330 

Signed-off-by: João Vanzuita <joao@kubeshop.io>

### CODE REVIEW

**Comment by converge** [comment]
without / with generated key:

```
developer@3de7acb6cf77:~/kubefirst$ git clone git@github.com:converge/test321.git
Cloning into 'test321'...
git@github.com: Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.
developer@3de7acb6cf77:~/kubefirst$ vi ~/.ssh/id_ed25519.pub
developer@3de7acb6cf77:~/kubefirst$ git clone git@github.com:converge/test321.git
Cloning into 'test321'...
remote: Enumerating objects: 59, done.
remote: Counting objects: 100% (59/59), done.
remote: Compressing objects: 100% (23/23), done.
remote: Total 59 (delta 29), reused 54 (delta 24), pack-reused 0
Receiving objects: 100% (59/59), 4.77 KiB | 84.00 KiB/s, done.
Resolving deltas: 100% (29/29), done.
developer@3de7acb6cf77:~/kubefirst$
```

**Review by pagottoo — DISMISSED** [review]
lgtm

**Review by 6za — DISMISSED** [review]
lgtm

**Review by CristhianF7 — APPROVED** [review]
🚀

**Review by CristhianF7 — APPROVED** [review]

**Pull request merged**
