### PR TITLE
Allow templates to be version controlled by tags -  #227

### PR DESCRIPTION
**Pull request by 6za**
Add new flag to init:
```
--template-tag v1.8.x 
```

`--template-tag` will be used when cloning repos to use a frozen tag by default the same as the current cli version. 

Signed-off-by: 6za <53096417+6za@users.noreply.github.com>

### CODE REVIEW

**Comment by 6za** [comment]
Showing how new log appears: `gitops`
image

**Comment by 6za** [comment]
Metaphor:
image

**Comment by 6za** [comment]
Added fallback mechanism: 
```bash 
go run . init --admin-email someemail@domain.io --cloud aws --hosted-zone-name somehost.com --region us-east-1  --version-gitops not-branch --profile default
```

```
LOG: 2022/08/16 17:04:55.580452 /home/developer/app/internal/gitClient/git.go:102: Trying to clone branch(not-branch):https://github.com/kubefirst/gitops-template 
LOG: 2022/08/16 17:04:55.854315 /home/developer/app/internal/gitClient/git.go:109: error cloning gitops-template repository from github couldn't find remote ref "refs/heads/not-branch" at branch not-branch
LOG: 2022/08/16 17:04:55.854731 /home/developer/app/internal/gitClient/git.go:117: Trying to clone tag(not-branch):1.8.5 
LOG: 2022/08/16 17:04:56.410883 /home/developer/app/cmd/kubefirstTemplate.go:31: cloned gitops-template repository to directory /home/developer/.k1/gitops
LOG: 2022/08/16 17:04:56.411199 /home/developer/app/cmd/kubefirstTemplate.go:33: detokenizing /home/developer/.k1/gitops
LOG: 2022/08/16 17:04:56.429365 /home/developer/app/cmd/kubefirstTemplate.go:35: detokenization of /home/developer/.k1/gitops complete
LOG: 2022/08/16 17:04:56.432856 /home/developer/app/cmd/kubefirstTemplate.go:41: creating git remote gitlab
LOG: 2022/08/16 17:04:56.433130 /home/developer/app/cmd/kubefirstTemplate.go:42: git remote add gitlab at url  https://gitlab.6zray.kubefast.com/kubefirst/gitops.git
LOG: 2022/08/16 17:04:56.433760 /home/developer/app/cmd/kubefirstTemplate.go:53: creating git remote ssh://127.0.0.1:8022/gitops
LOG: 2022/08/16 17:04:56.434274 /home/developer/app/cmd/kubefirstTemplate.go:62: committing detokenized gitops content
LOG: 2022/08/16 17:04:56.562460 /home/developer/app/cmd/init.go:233: clone and detokenization of gitops-template repository complete
LOG: 2022/08/16 17:04:56.562841 /home/developer/app/cmd/init.go:237: cloning and detokenizing the metaphor-template repository
LOG: 2022/08/16 17:04:56.563076 /home/developer/app/internal/gitClient/git.go:117: Trying to clone tag():1.8.5 
LOG: 2022/08/16 17:04:57.182318 /home/developer/app/cmd/kubefirstTemplate.go:31: cloned metaphor-template repository to directory /home/developer/.k1/metaphor
LOG: 2022/08/16 17:04:57.182539 /home/developer/app/cmd/kubefirstTemplate.go:33: detokenizing /home/developer/.k1/metaphor
LOG: 2022/08/16 17:04:57.190807 /home/developer/app/cmd/kubefirstTemplate.go:35: detokenization of /home/developer/.k1/metaphor complete
LOG: 2022/08/16 17:04:57.193706 /home/developer/app/cmd/kubefirstTemplate.go:41: creating git remote gitlab
LOG: 2022/08/16 17:04:57.194042 /home/developer/app/cmd/kubefirstTemplate.go:42: git remote add gitlab at url  https://gitlab.6zray.kubefast.com/kubefirst/metaphor.git
LOG: 2022/08/16 17:04:57.194496 /home/developer/app/cmd/kubefirstTemplate.go:62: committing detokenized metaphor content
LOG: 2022/08/16 17:04:57.248197 /home/developer/app/cmd/init.go:239: clone and detokenization of metaphor-template repository complete

```

**Comment by 6za** [comment]
Added to ~/.kubefirst

```yaml 
git:
  clone:
    gitops:
      tag: 1.8.5
    metaphor:
      tag: 1.8.5
```

**Comment by 6za** [comment]
```yaml
...
git:
  clone:
    gitops:
      tag: 1.8.5
    metaphor:
      tag: 1.8.5
gitlab:
  local:
    service: http://localhost:8888
init:
  repos:
    gitops:
      cloned: true
      detokenized: true
    metaphor:
      cloned: true
      detokenized: true
log-folder-location: /home/developer/app/logs
template:
  tag: 1.8.5
vault:
  local:
    service: http://localhost:8200
version-gitops: not-branch
```

**Review by pagottoo — APPROVED** [review]

**Comment by 6za** [comment]
Full install done and worked as expected:
image
image

**Review by pagottoo — APPROVED** [review]
lgtm

**Pull request merged**
