### PR TITLE
Informer idea

### PR DESCRIPTION
**Pull request by 6za**
WIP

Signed-off-by: 6za <53096417+6za@users.noreply.github.com>

### CODE REVIEW

**Comment by 6za** [comment]
Required Artifacts on gitops: 
`registry/k1-ready.yaml`
```yaml 
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: k1-ready
  namespace: argocd
  finalizers:
  - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "40"
spec:
  project: default
  source:
    repoURL: <FULL_REPO_GITOPS_URL>
    path: components/k1-ready
    targetRevision: HEAD
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - Replace=true
      - PruneLast=true      
    retry:
      limit: 5
      backoff:
        duration: 5s
        maxDuration: 5m0s
        factor: 2
```


`components/k1-ready/cluster-role-binding.yaml`:
```yaml 
apiVersion: v1
kind: Pod
metadata:
  name: sample
  namespace: default
spec:
  containers:
# Image needs to come from install ECR not github, I believe...
   -  image: 6zar/k1test:latest
      name: k1-ready
      command: ["tail"]
      args: ["-f","/dev/null"]    
---
apiVersion: v1
kind: Pod
metadata:
  name: sample2
  namespace: default
spec:
  containers:
   -  image: 6zar/k1test:latest
      name: k1-ready
      command: ["tail"]
      args: ["-f","/dev/null"]  
```

`components/k1-ready/app.yaml`:
```yaml 
apiVersion: batch/v1
kind: Job
metadata:
  name: k1-ready
  namespace: default
  annotations:
    argocd.argoproj.io/sync-wave: "0"  
spec:
  template:
    spec:
      serviceAccountName: k1-ready    
      containers:
       -  image: 6zar/k1test:latest
          name: k1-ready
          imagePullPolicy: Always
          command: ["/usr/local/bin/kubefirst"]
          args: ["podinformer"]    
      restartPolicy: Never
  backoffLimit: 1  
```

**Comment by 6za** [comment]
Sample: 
image

**Comment by fharper** [comment]
@6za : if this PR is still a WIP, can we set it as draft please?

**Comment by 6za** [comment]
This PR was left open to help me to find the code and logic in use, this code was moved to another repo. Thanks for the reminder,

**Pull request closed without merging**
