### PR TITLE
Tweak to ensure tags work as expected

### PR DESCRIPTION
**Pull request by 6za**
Possible issue fix when running for the 1st 1.9.0. 

Signed-off-by: 6za <53096417+6za@users.noreply.github.com>

### CODE REVIEW

**Comment by 6za** [comment]
When cloning from a tag:

# Logs:
```
LOG: 2022/09/27 16:46:31.219690 /home/developer/app/cmd/init.go:177: ssh key pair creation complete
LOG: 2022/09/27 16:46:31.219899 /home/developer/app/internal/gitClient/git.go:221: Trying to clone tag():1.8.6 
LOG: 2022/09/27 16:46:32.155858 /home/developer/app/internal/gitClient/git.go:262: [101] error removing old branch: gitops, remove /home/developer/.k1/gitops/.git/refs/heads: directory not empty
LOG: 2022/09/27 16:46:32.163796 /home/developer/app/internal/repo/kubefirstTemplate.go:32: cloned gitops-template repository to directory /home/developer/.k1/gitops
```


# Git 

Only a main branch exist
```bash 
git branch

* main
```


# Why this is important?

Soft-serve/Argo gitops process seems to not like to have 2 branches around, confusing later steps on which we push the new gitops changes from detoken steps.

**Comment by 6za** [comment]
```
commit f1a7cd2125c854e579061fa0b2e1f59aad36e011 (HEAD -> main)
Author: kubefirst-bot <kubefirst-bot@kubefirst.com>
Date:   Tue Sep 27 16:46:32 2022 +0000

    committing detokenized gitops content

commit 4bd84e6dff176e7a3d54569455895f09211ededd (tag: 1.8.6)
```

**Comment by 6za** [comment]
So, as expected from a tag we created main and push will happen from `main` not the tag.

**Comment by 6za** [comment]
From a brach: 

```
LOG: 2022/09/27 16:55:30.229044 /home/developer/app/internal/gitClient/git.go:205: Trying to clone branch(main):https://github.com/kubefirst/gitops-template 
LOG: 2022/09/27 16:55:30.894349 /home/developer/app/internal/repo/kubefirstTemplate.go:32: cloned gitops-template repository to directory /home/developer/.k1/gitops
LOG: 2022/09/27 16:55:30.894568 /home/developer/app/internal/repo/kubefirstTemplate.go:34: detokenizing /home/developer/.k1/gitops
```

```
commit 8c14f41d862b5446806debc3f843b47a319f12c9 (HEAD -> main)
Author: kubefirst-bot <kubefirst-bot@kubefirst.com>
Date:   Tue Sep 27 16:55:31 2022 +0000

    committing detokenized gitops content

commit d748456f5c41efdec3c69b8160e52bd87b498d7a (origin/main)
```

```bash
git branch
* main
```

**Review by pagottoo — COMMENTED** [review]
lgtm

**Pull request merged**
